asyn:
  min_received_num: 10
  min_received_rate: -1.0
  timeout: 0
  use: true
attack:
  alpha_TV: 0.001
  alpha_prop_loss: 0
  attack_method: backdoor
  attacker_id: 1
  attackers_list: []
  classifier_PIA: randomforest
  dp_noise: -1.0
  edge_num: 100
  freq: 3
  info_diff_type: l2
  inject_round: 0
  insert_round: 100000
  krum: false
  label_type: dirty
  max_ite: 400
  mean:
  - 0.4914
  - 0.4822
  - 0.4465
  multi_krum: false
  norm_clip: false
  norm_clip_value: 5.0
  pgd_eps: 2
  pgd_lr: 0.1
  pgd_poisoning: false
  poison_ratio: 0.05
  reconstruct_lr: 0.01
  reconstruct_optim: Adam
  scale_para: 1.0
  scale_poisoning: false
  self_epoch: 6
  self_lr: 0.05
  self_opt: false
  setting: fix
  std:
  - 0.247
  - 0.2435
  - 0.2616
  target_label_ind: 7
  trigger_type: signalTrigger
  use_multi_attackers: false
backend: torch
cfg_file: ''
criterion:
  type: CrossEntropyLoss
data:
  args:
  - download: true
  batch_size: 64
  cSBM_phi:
  - 0.5
  - 0.5
  - 0.5
  consistent_label_distribution: true
  dataset:
  - train
  - val
  - test
  - poison
  do_sta: false
  drop_last: false
  graphsaint:
    num_steps: 30
    walk_length: 2
  labelwise_boxplot: false
  loader: ''
  num_workers: 0
  plot_boxplot: false
  pre_transform: []
  probe_label_dist: false
  quadratic:
    dim: 1
    max_curv: 12.5
    min_curv: 0.02
  root: data/
  seed: 1
  shuffle: true
  sizes:
  - 10
  - 5
  splits:
  - 1.0
  - 0.0
  - 0.0
  splitter: lda
  splitter_args:
  - alpha: 0.5
  subsample: 1.0
  target_transform: []
  transform:
  - - ToTensor
    - {}
  type: CIFAR10@torchvision
device: 1
distribute:
  use: false
early_stop:
  delta: 0.0
  improve_indicator_mode: best
  patience: 0
  the_smaller_the_better: true
eval:
  best_res_update_round_wise_key: test_loss
  freq: 100
  metrics:
  - acc
  - correct
  monitoring: []
  report:
  - weighted_avg
  - avg
  - fairness
  - raw
  save_data: false
  split:
  - test
  - poison
expname: backdoor_signalTrigger_fix/signal_ditto/12345
federate:
  batch_or_epoch: epoch
  client_num: 100
  data_weighted_aggr: false
  ignore_weight: false
  join_in_info: []
  local_update_steps: 2
  make_global_eval: false
  method: Ditto
  mode: standalone
  online_aggr: false
  restore_from: ''
  sample_client_num: 10
  sample_client_rate: 0.1
  save_to: ''
  share_local_model: false
  total_round_num: 100
  unseen_clients_rate: 0.0
  use_diff: false
  use_ss: false
  weight_avg: true
fedopt:
  use: false
fedprox:
  use: false
fedsageplus:
  a: 1.0
  b: 1.0
  c: 1.0
  fedgen_epoch: 200
  gen_hidden: 128
  hide_portion: 0.5
  loc_epoch: 1
  num_pred: 5
fedunlearn:
  loss_thresh: 0.2
  switch_rounds: 10
  trap_rate: 0.1
flitplus:
  factor_ema: 0.8
  lambdavat: 0.5
  tmpFed: 0.5
  weightReg: 1.0
gcflplus:
  EPS_1: 0.05
  EPS_2: 0.1
  seq_length: 5
  standardize: false
grad:
  grad_clip: 5.0
hpo:
  fedex:
    cutoff: 0.0
    diff: false
    eta0: -1.0
    flatten_ss: true
    gamma: 0.0
    num_arms: 16
    sched: auto
    ss: ''
    use: false
  init_cand_num: 16
  larger_better: false
  log_scale: false
  metric: client_summarized_weighted_avg.val_loss
  num_workers: 0
  pbt:
    max_stage: 5
    perf_threshold: 0.1
  plot_interval: 1
  scheduler: rs
  sha:
    budgets: []
    elim_rate: 3
    elim_round_num: 3
  ss: ''
  table:
    eps: 0.1
    idx: 0
    num: 27
    ss: ''
  working_folder: hpo
model:
  dropout: 0.0
  embed_size: 8
  graph_pooling: mean
  hidden: 512
  in_channels: 0
  layer: 2
  model_num_per_trainer: 1
  num_item: 0
  num_user: 0
  out_channels: 10
  task: node
  type: convnet2
  use_bias: true
nbafl:
  use: false
optimizer:
  lr: 0.1
  type: SGD
  weight_decay: 0.0
outdir: trytry/Ditto_convnet2_on_CIFAR10@torchvision_lr0.1_lepoch2/backdoor_signalTrigger_fix/signal_ditto/12345
personalization:
  K: 5
  beta: 1.0
  epoch_feature: 1
  epoch_linear: 2
  local_param: []
  local_update_steps: 2
  lr: 0.1
  lr_feature: 0.1
  lr_linear: 0.1
  regular_weight: 0.1
  share_non_trainable_para: false
  weight_decay: 0.0
regularizer:
  mu: 0.0
  type: ''
seed: 12345
sgdmf:
  use: false
trainer:
  finetune:
    before_eval: false
    epochs: 1
    freeze_param: ''
    lr: 0.01
    steps: 1
  type: cvtrainer
use_gpu: true
verbose: 1
vertical:
  use: false
wandb:
  use: false

