use_gpu: True
eval:
  freq: 10
  metrics: ['acc']

federate:
  mode: 'standalone'
  local_update_steps: 1
  total_round_num: 20
  batch_or_epoch: 'epoch'
  client_num: 5
  sample_client_rate: 0.2

data:
  root: 'data'
  type: 'IMDB@torchtext'
  splits: [0.6, 0.2, 0.2]
  batch_size: 10
  splitter: 'lda'
  splitter_args: [{'alpha': 0.5}]

model:
  type: 'gchhablani/bert-base-cased-finetuned-sst2@transformers'
  task: 'SequenceClassification'

optimizer:
  lr: 0.8
  weight_decay: 0.0

criterion:
  type: 'CrossEntropyLoss'

trainer:
  type: 'nlptrainer'