use_gpu: True
device: -1
early_stop:
  patience: 3
seed: 1
federate:
  mode: standalone
  local_update_steps: 1
  batch_or_epoch: epoch
  total_round_num: 100
  client_num: 100
  sample_client_rate: 0.2
  unseen_clients_rate: 0.2
data:
  root: 'glue'
  type: 'cola@huggingface_datasets'
  args: [{'used_train_ratio':0.5, 'max_len': 128, 'half_val_dummy_test': False, 'val_as_dummy_test': True, 'part_train_dummy_val': 0.1, 'part_train_dummy_test': 0} ]
  batch_size: 64
  splitter: 'lda'
  splitter_args: [ { 'alpha': 0.4, 'min_size': 1} ]
  num_workers: 0
model:
  type: 'google/bert_uncased_L-2_H-128_A-2@transformers'
  task: 'SequenceClassification'
  out_channels: 2
optimizer:
  lr: 0.1
  weight_decay: 0.0
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: nlptrainer
eval:
  freq: 5
  metrics: ['acc', 'correct', 'f1']
  split: ['val', 'train']
